SYNTHESIS=`pwd`
SRC=${SYNTHESIS}/sources
TESTS=${SYNTHESIS}/tests
DOC=${SYNTHESIS}/documentation
VCSNODE=${SYNTHESIS}/vcs
PROTO=${SYNTHESIS}/prototypes/
MIXINS=${SYNTHESIS}/mixins
TEST_EXE=${TESTS}/exe
SYNIMPDIR=$PROTO
SYNEXPDIR=$PROTO
SOURCE_PATH=${SRC},${MIXINS},${TESTS}
SLASH=/
RMCMD=rm -f
CPCMD=cp
DBG=-d
export SYNTHESIS SRC TESTS DOC VCSNODE PROTO MIXINS TEST_EXE SYNIMPDIR SYNEXPDIR SOURCE_PATH SLASH RMCMD DBG
